apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: healthcare-appointment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password@mongodb-service:27017/healthcare_appointments?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002